doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        driver: 'pdo_pgsql'
        charset: UTF8
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            PhotoInfrastructure:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Photo/Infrastructure/Doctrine/Entity'
                prefix: 'Photo\Infrastructure\Doctrine\Entity'
                alias: PhotoInfrastructure
            UserInfrastructure:
                is_bundle: false
                dir: '%kernel.project_dir%/src/User/Infrastructure/Doctrine/Entity'
                prefix: 'User\Infrastructure\Doctrine\Entity'
                alias: UserInfrastructure

when@test:
    doctrine:
        dbal:
            dbname_suffix: '_test'
