security:
    providers:
        app_user_provider:
            id: User\Infrastructure\Security\SecurityUserProvider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            custom_authenticators:
                - User\Infrastructure\Security\SessionAuthenticator
            logout:
                path: /logout
                target: /

    access_control:
        - { path: ^/profile, roles: ROLE_USER }
        - { path: ^/photos/import, roles: ROLE_USER }
        - { path: ^/photo/\d+/like, roles: ROLE_USER }
